PIC-4134 put service account name in pod name - useful for namespaces…
ministryofjustice/cloud-platform-terraform-service-pod pull request #18
Opened 2024-09-09 08:17 UTC by markreesmoj

… with multiple service accounts

2024-09-09 08:18 UTC, markreesmoj commented on main.tf
> +  identifier = "cp-${random_id.name.hex}"
Shortening the prefix to reduce the chance of hitting the 64 character limit
I wonder if the service name could replace the random_id part instead?

2024-09-10 08:10 UTC, jaskaransarkaria commented on main.tf
> +    name      = "${local.identifier}-${var.service_account_name}-service-pod"
```suggestion
    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```

2024-09-10 08:10 UTC, jaskaransarkaria commented on main.tf
> +        app = "${local.identifier}-${var.service_account_name}-service-pod"
```suggestion
    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```

2024-09-10 08:10 UTC, jaskaransarkaria commented on main.tf
> +          app = "${local.identifier}-${var.service_account_name}-service-pod"
```suggestion
    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```

2024-10-21 13:31 UTC, sj-williams commented on main.tf
> +    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```suggestion
    name      = var.service_account_name == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```

2024-10-21 13:31 UTC, sj-williams commented on main.tf
> +    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```suggestion
    name      = var.service_account_name == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```

2024-10-21 13:31 UTC, sj-williams commented on main.tf
> +    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```suggestion
    name      = var.service_account_name == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
```

2024-10-21 13:32 UTC, sj-williams requested changes

2024-10-21 13:32 UTC, sj-williams commented on main.tf
> +    name      = ${var.service_account_name} == "" ? "${local.identifier}-service-pod" : "${var.service_account_name}-service-pod"
@markreesmoj just spotted that these suggested changes were using the old interpolation syntax which is no longer supported outside of string expressions (see broken unit test actions). This should work though

2024-10-23 15:56 UTC, sj-williams approved these changes

2024-10-23 15:56 UTC, merged